name: Generate Integrations and Update README

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Generate integrations
        env:
          BOLTIC_TOKEN: ${{ secrets.BOLTIC_TOKEN }}
        run: npm run generate

      - name: Update README index
        run: npm run update:readme

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: regenerate integrations and update README index"

